layout_spectrum: 0.3618207
typography_spectrum: 0.4933276
color:
  saturation: 0.4590267
  lightness: 0.2604923
  brandStrength: 0.6739312
  rhythmicContrast: 0.4603658
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: My Journey
